# Generated by Django 4.0.6 on 2022-07-25 11:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('prep_time', models.FloatField(blank=True, null=True)),
                ('servings', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('ingredients', models.CharField(blank=True, max_length=2000, null=True)),
                ('instructions', models.CharField(blank=True, max_length=2000, null=True)),
                ('is_public', models.BooleanField(blank=True, default=False, null=True)),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
